# Generated by Django 4.2.4 on 2023-08-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('video_url', models.SlugField(verbose_name='ссылка на видео')),
                ('data_add', models.DateTimeField(auto_now_add=True, verbose_name='дата содания')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='лайки')),
                ('dis_likes', models.PositiveIntegerField(default=0, verbose_name='дислайки')),
                ('genres', models.ManyToManyField(blank=True, to='videos.genre', verbose_name='жанры')),
                ('tags', models.ManyToManyField(blank=True, to='videos.tag', verbose_name='теги')),
            ],
            options={
                'verbose_name': 'видео',
                'verbose_name_plural': 'видио',
                'ordering': ['data_add'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='текст коментария')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='лайки')),
                ('dis_likes', models.PositiveIntegerField(default=0, verbose_name='дислайки')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
            options={
                'verbose_name': 'коментарий',
                'verbose_name_plural': 'коментарии',
                'ordering': ['pk'],
            },
        ),
    ]
