# Generated by Django 4.2.4 on 2023-08-18 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TegType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тип',
                'verbose_name_plural': 'типы тегов',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.tegtype', verbose_name='тип'),
        ),
    ]
