# Generated by Django 4.2.4 on 2023-09-03 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0007_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='users_disliked',
            field=models.ManyToManyField(blank=True, related_name='disliked_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='users_liked',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='users_disliked',
            field=models.ManyToManyField(blank=True, related_name='disliked_video', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='users_liked',
            field=models.ManyToManyField(blank=True, related_name='liked_video', to=settings.AUTH_USER_MODEL),
        ),
    ]
